# Generated by Django 3.2.4 on 2021-08-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_address',
            new_name='shipping_address',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_company',
            new_name='shipping_company',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_country',
            new_name='shipping_country',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_email',
            new_name='shipping_email',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='shopping_phone',
            new_name='shipping_phone',
        ),
    ]
