# Generated by Django 3.2.4 on 2021-08-20 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
    ]
