# Generated by Django 3.2.4 on 2021-08-06 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='color',
            field=models.CharField(max_length=255, null=True, verbose_name='color'),
        ),
    ]
