# Generated by Django 3.2.4 on 2021-08-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_cartitems_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slide_image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images', verbose_name='image'),
        ),
    ]
